# Tensor
Tensor is the most basic data structure in PyTorch, similar to a multidimensional array. It can represent scalars, vectors, matrices, or arrays of arbitrary dimensions.
## Dimensions and Data Types
### Dimensions

In [1]:
import torch

# 创建0维张量（标量）
scalar = torch.tensor(5)
print("0维张量（标量）:")
print(scalar)
print("维度信息:", scalar.size())
print("轴数:", scalar.dim())

0维张量（标量）:
tensor(5)
维度信息: torch.Size([])
轴数: 0


In [2]:
# 创建1维张量（向量）
vector = torch.tensor([1, 2, 3, 4, 5])
print("1维张量（向量）:")
print(vector)
print("维度信息:", vector.size())
print("轴数:", vector.dim())

1维张量（向量）:
tensor([1, 2, 3, 4, 5])
维度信息: torch.Size([5])
轴数: 1


In [3]:
# 创建2维张量（矩阵）
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("2维张量（矩阵）:")
print(matrix)
print("维度信息:", matrix.size())
print("轴数:", matrix.dim())

2维张量（矩阵）:
tensor([[1, 2, 3],
        [4, 5, 6]])
维度信息: torch.Size([2, 3])
轴数: 2


In [4]:
# 创建3维张量
tensor_3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("维张量:")
print(tensor_3d)
print("维度信息:", tensor_3d.size())
print("轴数:", tensor_3d.dim())

维张量:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
维度信息: torch.Size([2, 2, 3])
轴数: 3


### Data Types
在创建张量时，可以通过指定dtype参数来设置所需的数据类型。例如，要创建一个64位浮点数张量，可以使用以下代码：

In [5]:
import torch

tensor = torch.tensor([1, 2, 3], dtype=torch.float64)
print(tensor)
print(tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


## GPU Acceleration
Check out the available GPUs

In [6]:
import torch

# 检测系统中是否有可用的GPU
if torch.cuda.is_available():
    # 输出可用的GPU设备数量
    print(f"GPU可用，可用的GPU设备数量：{torch.cuda.device_count()}")
    # 输出每个可用GPU设备的名称
    for i in range(torch.cuda.device_count()):
        print(f"GPU设备 {i}: {torch.cuda.get_device_name(i)}")
else:
    print("GPU不可用")

GPU可用，可用的GPU设备数量：1
GPU设备 0: NVIDIA GeForce RTX 3060 Laptop GPU


Move Tensor to GPU

In [7]:
import torch
 
# 检查GPU是否可用
if torch.cuda.is_available():
    # 创建一个张量并将其移动到GPU上
    tensor = torch.tensor([1, 2, 3])
    tensor = tensor.to('cuda')
    print(tensor)
 
    # 进行张量计算
    result = tensor * 2
    print(result)
 
    # 将张量移回CPU
    result = result.to('cpu')
    print(result)
else:
    print("GPU不可用")

tensor([1, 2, 3], device='cuda:0')
tensor([2, 4, 6], device='cuda:0')
tensor([2, 4, 6])


The classic "device" statement

In [8]:
import torch


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.tensor([1, 2, 3]).to(device)
result = x * 2
print(result)


tensor([2, 4, 6], device='cuda:0')
